version: "3.8"
services:
  frontend:
    image: "frontend-dev"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
  backend:
    image: backend-dev
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3005:3005"




